* Dynamic Segmentation Widget

WARNING: Experimental

This widget provides a button that can work with the [[http://blogs.esri.com/esri/arcgis/2011/08/19/a-server-object-extension-for-performing-dynamic-segmentation/][Dynamic Segmentation SOE]] developed by Sterling Quinn at Esri. The source code can be downloaded [[http://www.arcgis.com/home/item.html?id%3D2ccd7d9d70cf4284b41e45859d2870a0][here]]. 

** Usage

*** Install the Dynamic Segmentation server object extension on your ArcGIS Server instance

*** Publish a service containing M values to your ArcGIS Server and select the Dynamic Segmentation SOE option

*** Git clone or download and extract the zip file into your app's widget directory.

*** Add widget to your app like this

#+begin_src javascript
  var dynamicSegmentationButton = new DynamicSegmentation({
                   map: map,
                   routeService: routeService,
                   layerId: 0,
                   tolerance: 15
               }, 'buttonDiv');
#+End_src

** Contributions
This is still experimental. Issues and pull requests are welcome. 

** To Do

   - Write tests

   - Assign default style to button

   - Ask @Esri to add an open source license to the Dynamic Segmentation SOE

** License

Copyright 2015 Nick Peihl, San Juan County GIS

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

[[http://www.apache.org/licenses/LICENSE-2.0]]

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A copy of the license is available in the repository's license.txt file.
